import type { Exercise } from "./types.ts";
import benchPressVideo from "./assets/bench-press.mp4";

// Every exercise shares one video until the catalog gets its own footage.
const PLACEHOLDER_ASSET: Exercise["asset"] = {
  type: "video",
  url: benchPressVideo,
};

// TODO: надо добавлять новые данные и делать чистый красивый список упражнений
export const EXERCISES: Record<string, Exercise> = {
  ["tX9HxwCkIckqNaEaf2Dq"]: {
    id: "tX9HxwCkIckqNaEaf2Dq",
    name: "Бабочка в тренажёре",
    primaryMuscles: ["chest"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Vfh6Q6Lu2cabxPEtWoqW"]: {
    id: "Vfh6Q6Lu2cabxPEtWoqW",
    name: "Боковой подъём в тренажёре",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["dV1lK4mTcgk0hsXfiiLC"]: {
    id: "dV1lK4mTcgk0hsXfiiLC",
    name: "Вертикальная рычажная тяга в тренажёре",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["B4KWg9mb2s04WbukIzDj"]: {
    id: "B4KWg9mb2s04WbukIzDj",
    name: "Вертикальная тяга обратным хватом в блоке",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["AFfWN3dMGhlGyqOAwWXO"]: {
    id: "AFfWN3dMGhlGyqOAwWXO",
    name: "Вертикальная тяга узким хватом в блоке",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["7WHNH0KA8Fved2WkuQ1s"]: {
    id: "7WHNH0KA8Fved2WkuQ1s",
    name: "Вертикальная тяга широким хватом в блоке",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["mOgcynAZufVTTLxAiADV"]: {
    id: "mOgcynAZufVTTLxAiADV",
    name: "Выпады с гантелями",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["CH9xHvgvcnk3572Qh82q"]: {
    id: "CH9xHvgvcnk3572Qh82q",
    name: "Выпады со штангой",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Af6NznR8fSOPx5OwlFPp"]: {
    id: "Af6NznR8fSOPx5OwlFPp",
    name: "Горизонтальная тяга в тренажёре на широчайшие",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["TKCpwpwjAtyQOCYMR4jG"]: {
    id: "TKCpwpwjAtyQOCYMR4jG",
    name: "Горизонтальная тяга узким хватом в блоке",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["lats", "biceps", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["3bY5nU71Yn0AqqScQYUp"]: {
    id: "3bY5nU71Yn0AqqScQYUp",
    name: "Горизонтальный жим ногами в тренажёре",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["uTAoik0jk8O6L43JTxWm"]: {
    id: "uTAoik0jk8O6L43JTxWm",
    name: "Жим гантелей лёжа",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbell", "bench"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Lf2a6CaubEowWiwdb4R8"]: {
    id: "Lf2a6CaubEowWiwdb4R8",
    name: "Жим на грудь в тренажёре",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["h0rIMeYCULTorlXLyPYq"]: {
    id: "h0rIMeYCULTorlXLyPYq",
    name: "Жим на икры в тренажёре",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["vhrOc6gI5BNTrfTPamHa"]: {
    id: "vhrOc6gI5BNTrfTPamHa",
    name: "Жим ногами в тренажёре",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["WQldUrMtFqTRt9Mt7fpT"]: {
    id: "WQldUrMtFqTRt9Mt7fpT",
    name: "Жим с плеч сидя в тренажёре с блинами",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: ["triceps"],
    equipment: ["machine"],
    load: { type: "plates", sides: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["OvlOX8JCqg0lEuaPBU3G"]: {
    id: "OvlOX8JCqg0lEuaPBU3G",
    name: "Жим штанги лёжа",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["barbell", "bench"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [
      {
        id: "uTAoik0jk8O6L43JTxWm",
        benefits: "если скамья со штангой занята",
      },
      {
        id: "Lf2a6CaubEowWiwdb4R8",
        benefits: "проще по технике",
      },
    ],
    instructions: [
      "Лопатки сведены и прижаты, стопы всей подошвой в полу.",
      "Опускай штангу к нижней части груди, локти под 45° к корпусу.",
      "Не отрывай таз от скамьи и не выключай локти в верхней точке.",
    ],
  },
  ["6RvYYb7MsBwFBPOLQ7H7"]: {
    id: "6RvYYb7MsBwFBPOLQ7H7",
    name: "Наклонный жим в тренажёре",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["qH48LIq9CgYChb2N6EUM"]: {
    id: "qH48LIq9CgYChb2N6EUM",
    name: "Наклонный жим на икры в тренажёре с блинами",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "plates", sides: 2 },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Mu1R9Be1diBMSpxhbSAP"]: {
    id: "Mu1R9Be1diBMSpxhbSAP",
    name: "Наклонный жим с гантелями",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: ["dumbbell", "bench"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["sC31YlCwvicBjH6dbTTY"]: {
    id: "sC31YlCwvicBjH6dbTTY",
    name: "Наклонный жим со штангой",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["shoulders", "triceps"],
    equipment: ["barbell", "bench"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Nrpp8g2zRcs4qelsy9oy"]: {
    id: "Nrpp8g2zRcs4qelsy9oy",
    name: "Обратная разводка в кроссовере",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Q2movvKDbsVTORTCQ0xa"]: {
    id: "Q2movvKDbsVTORTCQ0xa",
    name: "Обратная разводка в тренажёре",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["3RomG9bWZnkZGDDNV9eq"]: {
    id: "3RomG9bWZnkZGDDNV9eq",
    name: "Отведение бедра в тренажёре",
    primaryMuscles: ["abductors"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["P03Q501AwZPPL5s7sLN5"]: {
    id: "P03Q501AwZPPL5s7sLN5",
    name: "Отжимания на брусьях",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps"],
    equipment: [],
    load: { type: "plates", sides: 1 },
    weight: { type: "positive", selfWeightPercent: 100 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["umxNlS7G9eB12A5ChgcZ"]: {
    id: "umxNlS7G9eB12A5ChgcZ",
    name: "Перекрестный подъём рук с тросом",
    primaryMuscles: ["shoulders"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Wa6kyQhTiGRur6z8p7xZ"]: {
    id: "Wa6kyQhTiGRur6z8p7xZ",
    name: "Подтягивания нейтральным хватом",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["forearms", "biceps", "upper_back"],
    equipment: [],
    load: { type: "none" },
    weight: { type: "positive", selfWeightPercent: 100 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["7wGjDt7HL8RK8eu0Cfc7"]: {
    id: "7wGjDt7HL8RK8eu0Cfc7",
    name: "Подтягивания нейтральным хватом в гравитроне",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "forearms", "biceps"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "negative", selfWeightPercent: 100 },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["I4ThGLxJyoXzcFdfFfpO"]: {
    id: "I4ThGLxJyoXzcFdfFfpO",
    name: "Подтягивания обратным хватом",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps", "forearms"],
    equipment: [],
    load: { type: "none" },
    weight: { type: "positive", selfWeightPercent: 100 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["aPtSAO6ZEBZ2401nIDLK"]: {
    id: "aPtSAO6ZEBZ2401nIDLK",
    name: "Подтягивания обратным хватом в гравитроне",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["upper_back", "biceps", "forearms"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "positive", selfWeightPercent: 100 },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["md6HLXAXou4SEwRPjssW"]: {
    id: "md6HLXAXou4SEwRPjssW",
    name: "Подтягивания прямым хватом",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["forearms", "biceps", "upper_back"],
    equipment: [],
    load: { type: "none" },
    weight: { type: "positive", selfWeightPercent: 100 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["RRsBEHSyiYyZ6KsCt2LE"]: {
    id: "RRsBEHSyiYyZ6KsCt2LE",
    name: "Подтягивания прямым хватом в гравитроне",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps", "upper_back"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "negative", selfWeightPercent: 100 },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["4X0R7S4Xf4Iov5NC6oI3"]: {
    id: "4X0R7S4Xf4Iov5NC6oI3",
    name: "Подъём на носки сидя с блинами",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: [],
    load: { type: "plates", sides: 1 },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["tYCzxni00QUvnavXoGXf"]: {
    id: "tYCzxni00QUvnavXoGXf",
    name: "Приседания",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes"],
    equipment: [],
    load: { type: "none" },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["rwUri6ZQG6QTXGCvghCs"]: {
    id: "rwUri6ZQG6QTXGCvghCs",
    name: "Присяд в смитте",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["machine"],
    load: { type: "plates", sides: 2 },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["xxHwgWeeI6V29ktq6jA6"]: {
    id: "xxHwgWeeI6V29ktq6jA6",
    name: "Присяд с гантелью",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 1 },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["Txx1kCEjSmank1XX1aCP"]: {
    id: "Txx1kCEjSmank1XX1aCP",
    name: "Присяд со штангой",
    primaryMuscles: ["quadriceps"],
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["P6WeZVykfwg8kSKaz5XC"]: {
    id: "P6WeZVykfwg8kSKaz5XC",
    name: "Разгибание рук на трицепс с канатом",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["z9zakVGsyY2ep6UjHK7p"]: {
    id: "z9zakVGsyY2ep6UjHK7p",
    name: "Разгибание спины с блинами",
    primaryMuscles: ["lower_back"],
    secondaryMuscles: ["glutes"],
    equipment: [],
    load: { type: "plates", sides: 1 },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["ggcXFWpLVUYrGCjEp1Lv"]: {
    id: "ggcXFWpLVUYrGCjEp1Lv",
    name: "Румынская тяга с гантелями",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower_back", "upper_back", "lats"],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["MLuzrGdsEwJteUk0nruP"]: {
    id: "MLuzrGdsEwJteUk0nruP",
    name: "Румынская тяга со штангой",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower_back", "upper_back", "lats"],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["NMTsFqktmHGxma2iVRg5"]: {
    id: "NMTsFqktmHGxma2iVRg5",
    name: "Сведение бедра в тренажёре",
    primaryMuscles: ["adductors"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["EEK0B2o9CHg6ChdsvLwC"]: {
    id: "EEK0B2o9CHg6ChdsvLwC",
    name: "Сгибание ног лёжа в тренажёре",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["calves"],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["UDtwGTMbaOl6S0ISzCIR"]: {
    id: "UDtwGTMbaOl6S0ISzCIR",
    name: "Сгибание рук молотком с гантелями",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["OH3Eqq6aoMZgoPfoz5UG"]: {
    id: "OH3Eqq6aoMZgoPfoz5UG",
    name: "Сгибание рук на бицепс в тренажёре Скотта",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "stack" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["7WCTbCIAHhMaImG1FdCN"]: {
    id: "7WCTbCIAHhMaImG1FdCN",
    name: "Сгибание рук с EZ-штангой на бицепс",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["TIei5nUKqsyTyJ6H64Il"]: {
    id: "TIei5nUKqsyTyJ6H64Il",
    name: "Сгибание рук с гантелями на бицепс",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["0wWn5uJfI6Ge8znBQdYG"]: {
    id: "0wWn5uJfI6Ge8znBQdYG",
    name: "Сгибание рук со штангой на бицепс",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["hmOdrzGUqGptmXEwWqnP"]: {
    id: "hmOdrzGUqGptmXEwWqnP",
    name: "Скручивания в тренажёре с блинами",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["machine"],
    load: { type: "plates", sides: 2 },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["qgjsNpa5H5b9kK8LrJNX"]: {
    id: "qgjsNpa5H5b9kK8LrJNX",
    name: "Скручивания с блинами",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: [],
    load: { type: "plates", sides: 1 },
    weight: { type: "positive", selfWeightPercent: 25 },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["IVaM6rdC8hATlS2eCeYB"]: {
    id: "IVaM6rdC8hATlS2eCeYB",
    name: "Становая тяга с гантелями",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [
      "hamstrings",
      "lats",
      "quadriceps",
      "lower_back",
      "upper_back",
      "traps",
    ],
    equipment: ["dumbbell"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["CrFwcUXnZwW86TyzXato"]: {
    id: "CrFwcUXnZwW86TyzXato",
    name: "Становая тяга со штангой",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [
      "hamstrings",
      "quadriceps",
      "lower_back",
      "upper_back",
      "lats",
      "traps",
    ],
    equipment: ["barbell"],
    load: { type: "barbell" },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["2ObehYShK7vnWiyokEwt"]: {
    id: "2ObehYShK7vnWiyokEwt",
    name: "Тяга на наклонной скамье с гантелями",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["lats", "biceps", "forearms"],
    equipment: ["dumbbell", "bench"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 6, max: 8 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
  ["XVzH36BNcxpFRe8zloJ8"]: {
    id: "XVzH36BNcxpFRe8zloJ8",
    name: "Французский жим лёжа с гантелями",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
    load: { type: "dumbbell", count: 2 },
    weight: { type: "full" },
    reps: { min: 10, max: 12 },
    asset: PLACEHOLDER_ASSET,
    alternatives: [],
    instructions: [],
  },
};
