// Generated by scripts/prepare-exercise-images.mjs — do not edit.

import bench_pressStart from "./assets/bench-press-start.webp";
import bench_pressEnd from "./assets/bench-press-end.webp";
import biceps_curlStart from "./assets/biceps-curl-start.webp";
import biceps_curlEnd from "./assets/biceps-curl-end.webp";
import incline_bench_pressStart from "./assets/incline-bench-press-start.webp";
import incline_bench_pressEnd from "./assets/incline-bench-press-end.webp";
import lat_pulldownStart from "./assets/lat-pulldown-start.webp";
import lat_pulldownEnd from "./assets/lat-pulldown-end.webp";
import lateral_raiseStart from "./assets/lateral-raise-start.webp";
import lateral_raiseEnd from "./assets/lateral-raise-end.webp";
import preacher_curlStart from "./assets/preacher-curl-start.webp";
import preacher_curlEnd from "./assets/preacher-curl-end.webp";
import triceps_pushdownStart from "./assets/triceps-pushdown-start.webp";
import triceps_pushdownEnd from "./assets/triceps-pushdown-end.webp";

export const EXERCISE_FRAMES = {
  bench_press: { start: bench_pressStart, end: bench_pressEnd },
  biceps_curl: { start: biceps_curlStart, end: biceps_curlEnd },
  incline_bench_press: { start: incline_bench_pressStart, end: incline_bench_pressEnd },
  lat_pulldown: { start: lat_pulldownStart, end: lat_pulldownEnd },
  lateral_raise: { start: lateral_raiseStart, end: lateral_raiseEnd },
  preacher_curl: { start: preacher_curlStart, end: preacher_curlEnd },
  triceps_pushdown: { start: triceps_pushdownStart, end: triceps_pushdownEnd },
};
