import { EXERCISE_FRAMES } from "../frames.generated.ts";
import { crossFade } from "./assets.ts";
import type { ExerciseGroup } from "./types.ts";

export const ARM_GROUPS: ExerciseGroup[] = [
  {
    exercises: {
      dumbbell_curl: {
        name: "Подъём гантелей на бицепс стоя",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "базовый вариант, всегда есть свободные гантели",
        asset: crossFade(EXERCISE_FRAMES.dumbbell_curl),
        instructions: [
          "Локти прижаты к корпусу и остаются на месте всё движение.",
          "Поднимай гантели за счёт бицепса, не подкидывая их корпусом.",
          "Опускай медленнее, чем поднимаешь, до полного выпрямления рук.",
        ],
      },
      incline_dumbbell_curl: {
        name: "Подъём гантелей на бицепс на наклонной скамье",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "бицепс работает из растянутого положения",
        asset: crossFade(EXERCISE_FRAMES.incline_dumbbell_curl),
        instructions: [
          "Наклон скамьи 45–60°, руки свободно висят за линией корпуса.",
          "Сгибай руки, не двигая плечами вперёд.",
          "Опускай до полного выпрямления, сохраняя натяжение.",
        ],
      },
      hammer_curl: {
        name: "Сгибание рук «молотком» с гантелями",
        primaryMuscles: ["biceps", "forearms"],
        secondaryMuscles: [],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "добавляет толщину руке за счёт брахиалиса",
        asset: crossFade(EXERCISE_FRAMES.hammer_curl),
        instructions: [
          "Ладони смотрят друг на друга и не разворачиваются.",
          "Сгибай руки, держа локти у корпуса.",
          "Не раскачивай корпус и не выводи локти вперёд.",
        ],
      },
      ez_bar_curl: {
        name: "Подъём штанги на бицепс стоя с EZ-грифом",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "больше вес, чем с гантелями, и мягче для запястий",
        instructions: [
          "Хват на изгибах грифа, локти прижаты к бокам.",
          "Поднимай штангу до уровня груди, не выводя локти вперёд.",
          "Опускай до почти прямых рук, не бросая вес вниз.",
        ],
      },
      barbell_curl: {
        name: "Подъём штанги на бицепс стоя с прямым грифом",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "максимальная нагрузка на бицепс при прямом запястье",
        asset: crossFade(EXERCISE_FRAMES.barbell_curl),
        instructions: [
          "Хват на ширине плеч, локти у корпуса, спина прямая.",
          "Поднимай штангу силой бицепса, корпус неподвижен.",
          "Если запястья болят — переходи на EZ-гриф.",
        ],
      },
      preacher_curl: {
        name: "Сгибание рук на скамье Скотта со штангой",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 10, max: 12 },
        benefit: "исключает раскачку корпусом",
        asset: crossFade(EXERCISE_FRAMES.preacher_curl),
        instructions: [
          "Подмышки лежат на верхнем краю пюпитра, плечи не отрываются.",
          "Разгибай руки почти полностью, но не бросай вес в нижней точке.",
          "Не вставай с места и не помогай себе корпусом.",
        ],
      },
      preacher_dumbbell_curl: {
        name: "Сгибание рук на скамье Скотта с гантелью одной рукой",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 1 },
        reps: { min: 10, max: 12 },
        benefit: "видно разницу между руками и можно её добрать",
        instructions: [
          "Положи плечо на пюпитр, гантель в опущенной руке.",
          "Сгибай руку до уровня плеча, не отрывая локоть от подушки.",
          "Опускай медленно: в нижней точке бицепс наиболее уязвим.",
        ],
      },
      preacher_curl_machine: {
        name: "Сгибание рук на скамье Скотта в тренажёре",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "натяжение есть и в нижней точке, вес меняется мгновенно",
        asset: crossFade(EXERCISE_FRAMES.preacher_curl_machine),
        instructions: [
          "Отрегулируй сиденье: локти на подушке, ось совпадает с локтем.",
          "Сгибай руки до верхней точки и держи паузу полсекунды.",
          "Возвращай вес медленно, не давая стеку стукнуть.",
        ],
      },
      cable_curl: {
        name: "Сгибание рук на нижнем блоке стоя",
        primaryMuscles: ["biceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "равномерное натяжение во всей амплитуде",
        asset: crossFade(EXERCISE_FRAMES.cable_curl),
        instructions: [
          "Возьми прямую рукоять нижнего блока, локти у корпуса.",
          "Сгибай руки до уровня груди, корпус не двигается.",
          "Не отходи от стойки далеко — трос должен идти вдоль ног.",
        ],
      },
      cable_rope_curl: {
        name: "Сгибание рук на нижнем блоке стоя с канатом",
        primaryMuscles: ["biceps", "forearms"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "нейтральный хват и свободные запястья",
        asset: crossFade(EXERCISE_FRAMES.cable_rope_curl),
        instructions: [
          "Возьми канат нейтральным хватом, локти прижаты к бокам.",
          "Сгибай руки, разводя концы каната в верхней точке.",
          "Не тяни канат плечами вверх.",
        ],
      },
    },
  },
  {
    exercises: {
      triceps_pushdown_rope: {
        name: "Разгибание рук на верхнем блоке с канатом",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "свободные запястья и полное сокращение внизу",
        asset: crossFade(EXERCISE_FRAMES.triceps_pushdown_rope),
        instructions: [
          "Локти прижаты к бокам и не двигаются вперёд-назад.",
          "Разгибай руки до конца, в нижней точке коротко напряги трицепс.",
          "Не наваливайся на рукоять корпусом, работай только предплечьями.",
        ],
      },
      triceps_pushdown_bar: {
        name: "Разгибание рук на верхнем блоке с прямой рукоятью",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "держит больший вес, чем канат",
        asset: crossFade(EXERCISE_FRAMES.triceps_pushdown_bar),
        instructions: [
          "Хват на ширине плеч сверху, локти у корпуса.",
          "Разгибай руки до прямых, не двигая плечами.",
          "Возвращай рукоять до угла 90° в локте и не выше.",
        ],
      },
      triceps_pushdown_v_bar: {
        name: "Разгибание рук на верхнем блоке с V-рукоятью",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "компромисс между канатом и прямой рукоятью",
        asset: crossFade(EXERCISE_FRAMES.triceps_pushdown_v_bar),
        instructions: [
          "Возьмись за изгибы рукояти, кисти чуть развёрнуты внутрь.",
          "Разгибай руки до конца, локти прижаты к бокам.",
          "Не поднимай плечи и не наклоняйся вперёд.",
        ],
      },
      triceps_pushdown_reverse: {
        name: "Разгибание руки на верхнем блоке обратным хватом",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["forearms"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "акцент на медиальный пучок, работает каждая рука отдельно",
        asset: crossFade(EXERCISE_FRAMES.triceps_pushdown_reverse),
        instructions: [
          "Возьми рукоять снизу ладонью вверх, локоть прижми к боку.",
          "Разгибай руку до конца, не проворачивая кисть.",
          "Вес бери заметно меньше, чем в обычной версии.",
        ],
      },
      ez_bar_skullcrusher: {
        name: "Французский жим с EZ-штангой лёжа",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "растягивает трицепс под нагрузкой",
        instructions: [
          "Штанга над плечами, хват на изгибах, локти смотрят вперёд.",
          "Опускай гриф ко лбу или чуть за голову, плечи неподвижны.",
          "Не разводи локти в стороны и не превращай в жим.",
        ],
      },
      dumbbell_skullcrusher: {
        name: "Французский жим с гантелями лёжа",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "мягче для локтей, руки работают независимо",
        asset: crossFade(EXERCISE_FRAMES.dumbbell_skullcrusher),
        instructions: [
          "Гантели над плечами нейтральным хватом, локти вперёд.",
          "Опускай гантели к ушам, сохраняя плечи на месте.",
          "Разгибай руки до конца, но не бей гантелями друг о друга.",
        ],
      },
      overhead_dumbbell_extension: {
        name: "Разгибание руки из-за головы с гантелью сидя",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 1 },
        reps: { min: 10, max: 12 },
        benefit: "длинная головка трицепса в максимальном растяжении",
        asset: crossFade(EXERCISE_FRAMES.overhead_dumbbell_extension),
        instructions: [
          "Сядь со спинкой, гантель за головой, локоть смотрит вверх.",
          "Разгибай руку вверх, плечо остаётся вертикальным.",
          "Не отводи локоть в сторону и не прогибай поясницу.",
        ],
      },
      overhead_rope_extension: {
        name: "Разгибание рук из-за головы на блоке с канатом",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "растяжение плюс постоянное натяжение троса",
        instructions: [
          "Развернись спиной к стойке, канат за головой, шаг вперёд.",
          "Разгибай руки вперёд-вверх, локти держи рядом с головой.",
          "Корпус наклонён, но неподвижен: работают только предплечья.",
        ],
      },
      triceps_extension_machine: {
        name: "Разгибание рук в тренажёре сидя",
        primaryMuscles: ["triceps"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "локти зафиксированы, техника не ломается на усталости",
        asset: crossFade(EXERCISE_FRAMES.triceps_extension_machine),
        instructions: [
          "Отрегулируй сиденье: локти лежат на подушке, ось совпадает с локтем.",
          "Разгибай руки до конца, не отрывая локти от опоры.",
          "Возвращай вес медленно, не роняя стек.",
        ],
      },
      close_grip_bench_press: {
        name: "Жим штанги лёжа узким хватом",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders"],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 6, max: 10 },
        benefit: "самый большой вес на трицепс",
        asset: crossFade(EXERCISE_FRAMES.close_grip_bench_press),
        instructions: [
          "Хват на ширине плеч, не уже: узкий хват грузит запястья.",
          "Опускай штангу к низу груди, локти идут вдоль корпуса.",
          "Не разводи локти в стороны, иначе работу заберёт грудь.",
        ],
      },
      smith_close_grip_bench_press: {
        name: "Жим лёжа узким хватом в Смите",
        primaryMuscles: ["triceps"],
        secondaryMuscles: ["chest", "shoulders"],
        equipment: ["smith", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "можно дожимать до отказа в одиночку",
        asset: crossFade(EXERCISE_FRAMES.smith_close_grip_bench_press),
        instructions: [
          "Поставь скамью так, чтобы гриф шёл к низу груди.",
          "Хват на ширине плеч, локти вдоль корпуса.",
          "Ставь крючки так, чтобы дотянуться до них уставшими руками.",
        ],
      },
    },
  },
];
