import { EXERCISE_FRAMES } from "../frames.generated.ts";
import { crossFade } from "./assets.ts";
import type { ExerciseGroup } from "./types.ts";

export const BACK_GROUPS: ExerciseGroup[] = [
  {
    exercises: {
      pull_up_wide: {
        name: "Подтягивания широким хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "none" },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 6, max: 10 },
        benefit: "шире широчайшие, меньше работы бицепсом",
        related: ["lat_pulldown_wide", "assisted_pull_up_wide"],
        instructions: [
          "Хват чуть шире плеч, лопатки опущены до начала движения.",
          "Тяни локтями вниз, пока подбородок не окажется выше перекладины.",
          "Не раскачивайся и опускайся до полного выпрямления рук.",
        ],
      },
      pull_up_underhand: {
        name: "Подтягивания обратным хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "none" },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 6, max: 10 },
        benefit: "сильнее бицепс, обычно выходит больше повторов",
        instructions: [
          "Хват на ширине плеч ладонями к себе.",
          "Тяни локти вниз и назад, грудь веди к перекладине.",
          "Не заваливай корпус назад, чтобы добрать последние повторы.",
        ],
      },
      pull_up_parallel: {
        name: "Подтягивания параллельным хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "none" },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 6, max: 10 },
        benefit: "мягче всего для плеча и локтя",
        instructions: [
          "Возьмись за параллельные ручки, ладони смотрят друг на друга.",
          "Тяни себя вверх, ведя локти строго вдоль корпуса.",
          "Держи корпус ровным, не выкручивая плечи вперёд.",
        ],
      },
      weighted_pull_up_wide: {
        name: "Подтягивания широким хватом с отягощением",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "plates", sides: 1 },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 5, max: 8 },
        benefit: "прогрессия, когда свой вес стал лёгким",
        instructions: [
          "Повесь блин на пояс, проверь, что он не мешает ногам.",
          "Работай в той же технике, но без рывков в старте.",
          "Добавляй вес, только если делаешь 10 чистых повторов без него.",
        ],
      },
      weighted_pull_up_underhand: {
        name: "Подтягивания обратным хватом с отягощением",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "plates", sides: 1 },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 5, max: 8 },
        benefit: "самый тяжёлый вес из всех подтягиваний",
        instructions: [
          "Повесь блин на пояс, хват ладонями к себе на ширине плеч.",
          "Тяни грудью к перекладине, локти идут вниз и назад.",
          "Следи за локтями: с весом их легко перегрузить в нижней точке.",
        ],
      },
      weighted_pull_up_parallel: {
        name: "Подтягивания параллельным хватом с отягощением",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["bodyweight"],
        load: { type: "plates", sides: 1 },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 5, max: 8 },
        benefit: "тяжёлый вес в самом щадящем для суставов хвате",
        instructions: [
          "Повесь блин на пояс и возьмись за параллельные ручки.",
          "Тяни локти вдоль корпуса, корпус держи вертикально.",
          "Опускайся медленно: с весом соблазн бросить себя вниз сильнее.",
        ],
      },
      assisted_pull_up_wide: {
        name: "Подтягивания широким хватом в гравитроне",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        weight: { type: "negative", selfWeightPercent: 100 },
        reps: { min: 8, max: 12 },
        benefit: "если своим весом пока не выходит нужное число повторов",
        instructions: [
          "Встань коленями на платформу, хват чуть шире плеч.",
          "Тяни локтями вниз, платформа помогает ровно столько, сколько нужно.",
          "Снижай противовес от тренировки к тренировке — это прогрессия.",
        ],
      },
      assisted_pull_up_underhand: {
        name: "Подтягивания обратным хватом в гравитроне",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        weight: { type: "negative", selfWeightPercent: 100 },
        reps: { min: 8, max: 12 },
        benefit: "облегчённая версия с акцентом на бицепс",
        instructions: [
          "Встань на платформу, хват ладонями к себе на ширине плеч.",
          "Веди грудь к рукояти, локти вниз вдоль корпуса.",
          "Не отталкивайся ногами от платформы сильнее, чем нужно.",
        ],
      },
      assisted_pull_up_parallel: {
        name: "Подтягивания параллельным хватом в гравитроне",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        weight: { type: "negative", selfWeightPercent: 100 },
        reps: { min: 8, max: 12 },
        benefit: "облегчение плюс нейтральный хват — легче всего для плеча",
        instructions: [
          "Встань коленями на платформу, возьмись за параллельные ручки.",
          "Тяни себя вверх до касания грудью уровня ручек.",
          "Держи корпус вертикально, не отклоняясь назад.",
        ],
      },
    },
  },
  {
    exercises: {
      lat_pulldown_wide: {
        name: "Тяга верхнего блока к груди широким хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "любой вес и никакой зависимости от своего веса",
        related: ["pull_up_wide"],
        asset: crossFade(EXERCISE_FRAMES.lat_pulldown),
        instructions: [
          "Хват шире плеч, бёдра под валиками, корпус чуть отклонён назад.",
          "Тяни локтями вниз к рёбрам, доводя рукоять до верха груди.",
          "Не раскачивайся корпусом и не тяни рукоять за голову.",
        ],
      },
      lat_pulldown_underhand: {
        name: "Тяга верхнего блока обратным хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "сильнее включается бицепс и низ широчайших",
        instructions: [
          "Хват ладонями к себе на ширине плеч, бёдра под валиками.",
          "Тяни рукоять к низу груди, локти идут вдоль корпуса.",
          "Не отклоняй корпус назад больше чем на 15–20°.",
        ],
      },
      lat_pulldown_close: {
        name: "Тяга верхнего блока узким параллельным хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "длиннее амплитуда, широчайшие тянутся сильнее",
        instructions: [
          "Возьми V-рукоять, бёдра зафиксируй под валиками.",
          "Тяни рукоять к верху живота, локти вниз и назад.",
          "В верхней точке дай плечам подняться и растянуть широчайшие.",
        ],
      },
      lat_pulldown_single: {
        name: "Тяга верхнего блока одной рукой",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "выравнивает разницу между сторонами",
        instructions: [
          "Возьми одну рукоять, второй рукой держись за сиденье.",
          "Тяни локоть вниз к боку, не разворачивая корпус.",
          "Делай одинаковое число повторов на обе стороны.",
        ],
      },
      vertical_traction_stack: {
        name: "Вертикальная тяга в тренажёре с блоком",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "упор в грудь: корпус не помогает вообще",
        instructions: [
          "Отрегулируй сиденье: ручки чуть выше вытянутых рук.",
          "Тяни ручки вниз к плечам, грудь прижата к упору.",
          "Не тяни подбородком и не сутулься в нижней точке.",
        ],
      },
      vertical_traction_plates: {
        name: "Вертикальная тяга в тренажёре с блинами",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "тяжёлая вертикальная тяга с упором в грудь",
        instructions: [
          "Сядь, грудь прижата к упору, возьмись за верхние ручки.",
          "Тяни вниз, сводя лопатки, локти идут вдоль корпуса.",
          "Возвращай вес до конца, не бросая его в верхней точке.",
        ],
      },
    },
  },
  {
    exercises: {
      barbell_row: {
        name: "Тяга штанги в наклоне",
        primaryMuscles: ["lats", "upper_back"],
        secondaryMuscles: ["biceps", "lower_back", "forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 6, max: 10 },
        benefit: "больше рабочий вес и вся спина разом",
        instructions: [
          "Наклон корпуса 45°, спина прямая, штанга под плечами.",
          "Тяни штангу к низу живота, сводя лопатки.",
          "Не выпрямляй корпус во время подхода и не тяни рывком.",
        ],
      },
      barbell_row_underhand: {
        name: "Тяга штанги в наклоне обратным хватом",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["biceps", "upper_back", "lower_back"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 6, max: 10 },
        benefit: "локти ближе к корпусу, больше работы широчайшим",
        instructions: [
          "Хват ладонями вперёд на ширине плеч, наклон около 45°.",
          "Тяни штангу к низу живота, локти скользят вдоль боков.",
          "Держи запястья прямыми, не заваливай их назад.",
        ],
      },
      smith_row: {
        name: "Тяга штанги в наклоне в Смите",
        primaryMuscles: ["lats", "upper_back"],
        secondaryMuscles: ["biceps", "forearms"],
        equipment: ["smith"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "не нужно держать траекторию, спина устаёт меньше",
        instructions: [
          "Встань так, чтобы гриф шёл к низу живота, наклон 45°.",
          "Тяни гриф к себе, сводя лопатки, корпус неподвижен.",
          "Не выпрямляйся, помогая себе поясницей.",
        ],
      },
      dumbbell_row: {
        name: "Тяга гантели в наклоне одной рукой",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps", "forearms"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 1 },
        reps: { min: 8, max: 12 },
        benefit: "длинная амплитуда и контроль каждой стороны отдельно",
        instructions: [
          "Упрись коленом и рукой в скамью, спина параллельна полу.",
          "Тяни гантель к поясу, локоть идёт вдоль корпуса.",
          "Не разворачивай корпус, вытягивая вес плечом.",
        ],
      },
      t_bar_row: {
        name: "Тяга Т-грифа",
        primaryMuscles: ["lats", "upper_back"],
        secondaryMuscles: ["biceps", "lower_back"],
        equipment: ["barbell"],
        load: { type: "plates", sides: 1 },
        reps: { min: 8, max: 12 },
        benefit: "тяжёлая тяга с нейтральным хватом",
        instructions: [
          "Встань над грифом, колени согнуты, спина прямая.",
          "Тяни рукоять к животу, локти близко к корпусу.",
          "Опускай вес до полного растяжения, не касаясь блинами пола.",
        ],
      },
      seated_cable_row_close: {
        name: "Тяга нижнего блока к поясу узким хватом",
        primaryMuscles: ["lats", "upper_back"],
        secondaryMuscles: ["biceps", "forearms"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "ровное натяжение и никакой нагрузки на поясницу",
        instructions: [
          "Возьми V-рукоять, колени чуть согнуты, спина прямая.",
          "Тяни рукоять к низу живота, сводя лопатки.",
          "Не отклоняйся назад корпусом и не сутулься на возврате.",
        ],
      },
      seated_cable_row_wide: {
        name: "Тяга нижнего блока к поясу широким хватом",
        primaryMuscles: ["upper_back"],
        secondaryMuscles: ["lats", "biceps", "shoulders"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "больше нагрузки на верх спины и задние дельты",
        instructions: [
          "Возьми прямую рукоять хватом шире плеч.",
          "Тяни к верху живота, разводя локти в стороны.",
          "Держи грудь раскрытой и не роняй плечи вперёд.",
        ],
      },
      seated_cable_row_single: {
        name: "Тяга нижнего блока одной рукой",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["upper_back", "biceps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "доводит отстающую сторону",
        instructions: [
          "Возьми одну рукоять, вторую руку положи на колено.",
          "Тяни локоть назад вдоль корпуса, плечо уходит назад.",
          "Не доворачивай корпус, чтобы добрать амплитуду.",
        ],
      },
      chest_supported_row_stack: {
        name: "Горизонтальная тяга в тренажёре с блоком",
        primaryMuscles: ["upper_back", "lats"],
        secondaryMuscles: ["biceps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "упор в грудь снимает нагрузку с поясницы",
        instructions: [
          "Отрегулируй сиденье: ручки на уровне середины груди.",
          "Тяни ручки назад, сводя лопатки, грудь от упора не отрывай.",
          "Не тяни плечами вверх и не откидывайся назад.",
        ],
      },
      chest_supported_row_plates: {
        name: "Горизонтальная тяга в тренажёре с блинами",
        primaryMuscles: ["upper_back", "lats"],
        secondaryMuscles: ["biceps"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "тяжёлая тяга без участия поясницы",
        instructions: [
          "Ляг грудью на упор, возьмись за ручки нужным хватом.",
          "Тяни до касания ручками корпуса, лопатки вместе.",
          "Возвращай вес до полного растяжения, но не бросай его.",
        ],
      },
    },
  },
  {
    exercises: {
      straight_arm_pulldown: {
        name: "Пуловер на верхнем блоке стоя",
        primaryMuscles: ["lats"],
        secondaryMuscles: ["triceps", "abs"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "широчайшие без участия бицепса",
        instructions: [
          "Встань в шаге от стойки, наклонись вперёд, руки прямые.",
          "Веди рукоять вниз к бёдрам, локти зафиксированы.",
          "Не сгибай руки и не приседай, помогая себе корпусом.",
        ],
      },
      dumbbell_pullover: {
        name: "Пуловер с гантелью лёжа",
        primaryMuscles: ["lats", "chest"],
        secondaryMuscles: ["triceps"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 1 },
        reps: { min: 10, max: 12 },
        benefit: "растягивает грудь и широчайшие одним движением",
        instructions: [
          "Ляг вдоль скамьи, гантель держи двумя руками над грудью.",
          "Опускай за голову до растяжения, локти чуть согнуты.",
          "Не прогибай поясницу, опускай ровно до комфортной точки.",
        ],
      },
    },
  },
  {
    exercises: {
      back_extension_weighted: {
        name: "Гиперэкстензия с блином",
        primaryMuscles: ["lower_back"],
        secondaryMuscles: ["glutes", "hamstrings"],
        equipment: ["bench"],
        load: { type: "plates", sides: 1 },
        weight: { type: "positive", selfWeightPercent: 55 },
        reps: { min: 10, max: 12 },
        benefit: "разгибатели с нормальной прогрессией по весу",
        instructions: [
          "Валики под бёдрами, блин прижат к груди крест-накрест.",
          "Опускайся до ощущения растяжения и поднимайся в прямую линию.",
          "Не переразгибайся вверху и не делай движение рывком.",
        ],
      },
      back_extension_machine: {
        name: "Разгибание корпуса в тренажёре сидя",
        primaryMuscles: ["lower_back"],
        secondaryMuscles: ["glutes"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "точная нагрузка на поясницу и никакой работы с полом",
        instructions: [
          "Сядь, упор на верх спины, таз зафиксирован валиком.",
          "Отклоняйся назад до прямой линии корпуса.",
          "Возвращайся медленно, не позволяя весу толкать себя вперёд.",
        ],
      },
    },
  },
  {
    exercises: {
      romanian_deadlift: {
        name: "Румынская тяга со штангой",
        primaryMuscles: ["hamstrings", "glutes"],
        secondaryMuscles: ["lower_back", "forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "главное движение на заднюю поверхность бедра",
        instructions: [
          "Ноги на ширине таза, колени мягкие и почти не сгибаются.",
          "Веди таз назад, опуская штангу вдоль ног до растяжения бедра.",
          "Спина прямая: круглая поясница — сразу снижай вес.",
        ],
      },
      dumbbell_romanian_deadlift: {
        name: "Румынская тяга с гантелями",
        primaryMuscles: ["hamstrings", "glutes"],
        secondaryMuscles: ["lower_back", "forearms"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "проще держать траекторию и не нужна стойка",
        instructions: [
          "Гантели у бёдер, лопатки сведены, колени мягкие.",
          "Отводи таз назад, гантели скользят вдоль ног.",
          "Не тянись вниз спиной: амплитуду задаёт растяжение бедра.",
        ],
      },
      smith_romanian_deadlift: {
        name: "Румынская тяга в Смите",
        primaryMuscles: ["hamstrings", "glutes"],
        secondaryMuscles: ["lower_back"],
        equipment: ["smith"],
        load: { type: "barbell" },
        reps: { min: 10, max: 12 },
        benefit: "траектория задана, можно думать только о бедре",
        instructions: [
          "Встань вплотную к грифу, он идёт ровно вдоль ног.",
          "Отводи таз назад, сохраняя мягкие колени.",
          "Не отклоняйся от грифа, иначе нагрузка уйдёт в поясницу.",
        ],
      },
      machine_romanian_deadlift: {
        name: "Румынская тяга в тренажёре с блинами",
        primaryMuscles: ["hamstrings", "glutes"],
        secondaryMuscles: ["lower_back"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 10, max: 12 },
        benefit: "спина разгружена, хват не ограничивает вес",
        instructions: [
          "Встань в тренажёр, возьмись за ручки, плечи под упорами.",
          "Веди таз назад, опускаясь до растяжения задней поверхности.",
          "Поднимайся за счёт бедра и ягодиц, а не за счёт рук.",
        ],
      },
      deadlift: {
        name: "Становая тяга со штангой",
        primaryMuscles: ["glutes", "hamstrings", "lower_back"],
        secondaryMuscles: ["upper_back", "quadriceps", "forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 4, max: 6 },
        benefit: "самый тяжёлый вес из всего, что есть в зале",
        instructions: [
          "Штанга над серединой стопы, хват чуть шире ног, спина прямая.",
          "Толкай пол ногами и одновременно разгибай таз.",
          "Не тяни спиной: если таз обгоняет плечи, вес слишком большой.",
        ],
      },
    },
  },
  {
    exercises: {
      dumbbell_shrug: {
        name: "Шраги с гантелями",
        primaryMuscles: ["traps"],
        secondaryMuscles: ["forearms"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "руки вдоль корпуса — самая удобная траектория",
        instructions: [
          "Гантели по бокам, руки прямые, плечи опущены.",
          "Поднимай плечи строго вверх, к ушам.",
          "Не вращай плечами и не помогай себе бицепсом.",
        ],
      },
      barbell_shrug: {
        name: "Шраги со штангой",
        primaryMuscles: ["traps"],
        secondaryMuscles: ["forearms"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 10, max: 12 },
        benefit: "больше вес, чем с гантелями",
        instructions: [
          "Штанга в опущенных руках перед бёдрами, хват чуть шире плеч.",
          "Поднимай плечи вверх, удерживая паузу в верхней точке.",
          "Не подключай поясницу, раскачивая штангу.",
        ],
      },
      smith_shrug: {
        name: "Шраги в Смите",
        primaryMuscles: ["traps"],
        secondaryMuscles: ["forearms"],
        equipment: ["smith"],
        load: { type: "barbell" },
        reps: { min: 12, max: 15 },
        benefit: "можно не думать о равновесии штанги",
        instructions: [
          "Встань так, чтобы гриф шёл вдоль бёдер, руки прямые.",
          "Поднимай плечи вверх, не сгибая локти.",
          "Опускай плечи до полного растяжения трапеций.",
        ],
      },
      cable_shrug: {
        name: "Шраги на нижнем блоке",
        primaryMuscles: ["traps"],
        secondaryMuscles: ["forearms"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "натяжение сохраняется в нижней точке",
        instructions: [
          "Возьми прямую рукоять нижнего блока, встань ровно.",
          "Поднимай плечи вверх, удерживая корпус неподвижным.",
          "Не отклоняйся назад, компенсируя тягу троса.",
        ],
      },
    },
  },
];
