import { EXERCISE_FRAMES } from "../frames.generated.ts";
import { crossFade } from "./assets.ts";
import type { ExerciseGroup } from "./types.ts";

export const CHEST_GROUPS: ExerciseGroup[] = [
  {
    exercises: {
      bench_press: {
        name: "Жим штанги лёжа",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 6, max: 8 },
        benefit: "больше рабочий вес",
        related: ["incline_bench_press"],
        asset: crossFade(EXERCISE_FRAMES.bench_press),
        instructions: [
          "Лопатки сведены и прижаты, стопы всей подошвой в полу.",
          "Опускай штангу к нижней части груди, локти под 45° к корпусу.",
          "Не отрывай таз от скамьи и не выключай локти в верхней точке.",
        ],
      },
      dumbbell_bench_press: {
        name: "Жим гантелей лёжа",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 8, max: 12 },
        benefit: "шире амплитуда, руки работают независимо",
        asset: crossFade(EXERCISE_FRAMES.dumbbell_bench_press),
        instructions: [
          "Ляг с гантелями у груди, подними их на прямые руки над плечами.",
          "Опускай до уровня груди, предплечья держи вертикально.",
          "Не сталкивай гантели вверху — держи их над плечами.",
        ],
      },
      smith_bench_press: {
        name: "Жим лёжа в Смите",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: ["smith", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "можно работать до отказа без страхующего",
        asset: crossFade(EXERCISE_FRAMES.smith_bench_press),
        instructions: [
          "Поставь скамью так, чтобы гриф опускался к нижней части груди.",
          "Сними гриф поворотом кисти, опускай до касания груди.",
          "Проверь крючки перед подходом: они должны быть ниже груди.",
        ],
      },
      chest_press_stack: {
        name: "Жим от груди в тренажёре с блоком",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "проще всего подобрать вес и добить мышцу в конце",
        asset: crossFade(EXERCISE_FRAMES.chest_press),
        instructions: [
          "Отрегулируй сиденье: ручки на уровне середины груди.",
          "Выжимай вперёд, в конце не выключай локти полностью.",
          "Не отрывай лопатки и затылок от спинки.",
        ],
      },
      chest_press_plates: {
        name: "Жим от груди в тренажёре с блинами",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["triceps", "shoulders"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "ощущается как свободный вес, но без страховки",
        asset: crossFade(EXERCISE_FRAMES.chest_press),
        instructions: [
          "Отрегулируй сиденье: ручки на уровне середины груди.",
          "Выжимай ручки вперёд и чуть внутрь, лопатки прижаты.",
          "Опускай медленно, не позволяй блинам бросать руки назад.",
        ],
      },
    },
  },
  {
    exercises: {
      incline_bench_press: {
        name: "Жим штанги на наклонной скамье",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 6, max: 8 },
        benefit: "больше нагрузки на верх груди",
        related: ["bench_press"],
        asset: crossFade(EXERCISE_FRAMES.incline_bench_press),
        instructions: [
          "Наклон скамьи 30–45°: выше — и работу забирают плечи.",
          "Опускай штангу к ключицам, а не к середине груди.",
          "Держи лопатки сведёнными, не проваливай плечи вперёд.",
        ],
      },
      incline_dumbbell_press: {
        name: "Жим гантелей на наклонной скамье",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 8, max: 12 },
        benefit: "верх груди и свободная траектория разом",
        asset: crossFade(EXERCISE_FRAMES.incline_dumbbell_press),
        instructions: [
          "Наклон 30–45°, гантели закинь на бёдра и вынеси коленями.",
          "Опускай до уровня верха груди, локти чуть вперёд от линии плеч.",
          "В верхней точке не заваливай гантели друг на друга.",
        ],
      },
      smith_incline_press: {
        name: "Жим на наклонной скамье в Смите",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: ["smith", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "фиксированная траектория на верх груди",
        asset: crossFade(EXERCISE_FRAMES.smith_incline_press),
        instructions: [
          "Поставь наклонную скамью так, чтобы гриф шёл к ключицам.",
          "Опускай к верху груди, не уводя гриф на шею.",
          "Ставь крючки на уровне, с которого сможешь выйти сам.",
        ],
      },
      incline_chest_press_plates: {
        name: "Жим на верх груди в тренажёре с блинами",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders", "triceps"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "верх груди без контроля траектории",
        instructions: [
          "Сядь плотно, ручки должны быть на уровне ключиц.",
          "Выжимай вверх и вперёд, лопатки не отрывай от спинки.",
          "Не помогай ногами, отталкиваясь от пола.",
        ],
      },
    },
  },
  {
    exercises: {
      dips: {
        name: "Отжимания на брусьях",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        equipment: ["bodyweight"],
        load: { type: "none" },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 8, max: 12 },
        benefit: "низ груди и трицепс своим весом",
        asset: crossFade(EXERCISE_FRAMES.dips),
        instructions: [
          "Выйди на прямые руки, плечи опущены, взгляд вперёд.",
          "Наклони корпус вперёд и опускайся, пока плечо не станет параллельно полу.",
          "Не проваливай плечи вниз в нижней точке и не болтай ногами.",
        ],
      },
      weighted_dips: {
        name: "Отжимания на брусьях с отягощением",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        equipment: ["bodyweight"],
        load: { type: "plates", sides: 1 },
        weight: { type: "positive", selfWeightPercent: 100 },
        reps: { min: 6, max: 10 },
        benefit: "прогрессия, когда свой вес стал лёгким",
        asset: crossFade(EXERCISE_FRAMES.dips),
        instructions: [
          "Повесь блин на пояс и проверь, что он не бьёт по коленям.",
          "Опускайся с наклоном вперёд, контролируя нижнюю точку.",
          "Добавляй вес, только когда чисто делаешь 12 повторов без него.",
        ],
      },
      assisted_dips: {
        name: "Отжимания на брусьях в гравитроне",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        equipment: ["machine"],
        load: { type: "stack" },
        weight: { type: "negative", selfWeightPercent: 100 },
        reps: { min: 8, max: 12 },
        benefit: "если своим весом пока не выходит нужное число повторов",
        instructions: [
          "Встань коленями на платформу и возьмись за брусья.",
          "Опускайся так же, как на обычных брусьях, с наклоном вперёд.",
          "Уменьшай противовес по мере роста силы — это и есть прогрессия.",
        ],
      },
      dip_machine_stack: {
        name: "Отжимания в тренажёре сидя с блоком",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "движение брусьев с любым весом, хоть совсем лёгким",
        asset: crossFade(EXERCISE_FRAMES.dip_machine),
        instructions: [
          "Сядь плотно к спинке, ручки возьми нейтральным хватом.",
          "Толкай ручки вниз до полного разгибания локтей.",
          "Не помогай корпусом, наваливаясь на ручки сверху.",
        ],
      },
      dip_machine_plates: {
        name: "Отжимания в тренажёре сидя с блинами",
        primaryMuscles: ["chest", "triceps"],
        secondaryMuscles: ["shoulders"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "тяжёлая версия движения брусьев сидя",
        asset: crossFade(EXERCISE_FRAMES.dip_machine),
        instructions: [
          "Отрегулируй сиденье так, чтобы ручки были на уровне груди.",
          "Толкай вниз, держа корпус прижатым к спинке.",
          "Возвращай вес медленно, не роняя ручки вверх.",
        ],
      },
    },
  },
  {
    exercises: {
      pec_deck: {
        name: "Сведение рук в тренажёре «бабочка»",
        primaryMuscles: ["chest"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "изоляция груди без риска уронить вес",
        instructions: [
          "Отрегулируй сиденье: ручки на уровне середины груди.",
          "Своди руки по дуге, слегка согнув локти и зафиксировав их.",
          "Не отрывай лопатки от спинки и не разгоняй вес рывком.",
        ],
      },
      cable_crossover: {
        name: "Сведение рук в кроссовере стоя",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "натяжение не пропадает во всей амплитуде",
        asset: crossFade(EXERCISE_FRAMES.cable_crossover),
        instructions: [
          "Блоки вверху, шаг вперёд, корпус слегка наклонён.",
          "Своди руки перед собой на уровне низа груди.",
          "Не тяни вес плечами и не выпрямляй корпус во время повтора.",
        ],
      },
      low_cable_crossover: {
        name: "Сведение рук в кроссовере снизу вверх",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "акцент на верх груди",
        instructions: [
          "Блоки внизу, ручки в опущенных руках, шаг вперёд.",
          "Веди руки вверх и внутрь, сводя их перед ключицами.",
          "Держи локти чуть согнутыми и не подключай плечи.",
        ],
      },
      dumbbell_fly: {
        name: "Разведение гантелей лёжа",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "растягивает грудь сильнее любого тренажёра",
        asset: crossFade(EXERCISE_FRAMES.dumbbell_fly),
        instructions: [
          "Руки над плечами, локти чуть согнуты и зафиксированы.",
          "Разводи по дуге до уровня плеч, чувствуя растяжение груди.",
          "Не превращай в жим: угол в локте не меняется.",
        ],
      },
      incline_dumbbell_fly: {
        name: "Разведение гантелей на наклонной скамье",
        primaryMuscles: ["chest"],
        secondaryMuscles: ["shoulders"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "растяжение с акцентом на верх груди",
        asset: crossFade(EXERCISE_FRAMES.incline_dumbbell_fly),
        instructions: [
          "Наклон 30°, гантели над плечами, локти мягко согнуты.",
          "Разводи по дуге, пока плечи не дойдут до уровня скамьи.",
          "Бери вес меньше, чем на плоской скамье: плечо уязвимее.",
        ],
      },
    },
  },
];
