import { EXERCISE_FRAMES } from "../frames.generated.ts";
import { crossFade } from "./assets.ts";
import type { ExerciseGroup } from "./types.ts";

export const LEG_GROUPS: ExerciseGroup[] = [
  {
    exercises: {
      back_squat: {
        name: "Приседания со штангой на спине",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings", "lower_back", "abs"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 6, max: 8 },
        benefit: "главное движение на ноги и самый большой вес",
        related: ["leg_press_plates"],
        asset: crossFade(EXERCISE_FRAMES.back_squat),
        instructions: [
          "Гриф на трапециях, лопатки сведены, стопы чуть шире таза.",
          "Садись, уводя таз назад и вниз, колени идут по направлению носков.",
          "Не заваливай корпус вперёд и не сводит колени внутрь при подъёме.",
        ],
      },
      front_squat: {
        name: "Фронтальные приседания со штангой",
        primaryMuscles: ["quadriceps"],
        secondaryMuscles: ["glutes", "abs", "upper_back"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 6, max: 8 },
        benefit: "больше квадрицепса, спина стоит вертикально",
        asset: crossFade(EXERCISE_FRAMES.front_squat),
        instructions: [
          "Гриф лежит на передних дельтах, локти высоко подняты.",
          "Садись строго вниз, держа корпус вертикально.",
          "Опускай локти — и штанга скатится: следи за ними до конца подхода.",
        ],
      },
      smith_squat: {
        name: "Приседания в Смите",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["smith"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "не нужно держать равновесие, можно вынести стопы вперёд",
        asset: crossFade(EXERCISE_FRAMES.smith_squat),
        instructions: [
          "Поставь стопы чуть впереди грифа, спина прижата к нему.",
          "Опускайся до параллели бедра с полом.",
          "Проверь страховочные упоры: они должны быть ниже нижней точки.",
        ],
      },
      hack_squat: {
        name: "Приседания в гакк-тренажёре",
        primaryMuscles: ["quadriceps"],
        secondaryMuscles: ["glutes"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "спина разгружена, квадрицепс получает всё",
        asset: crossFade(EXERCISE_FRAMES.hack_squat),
        instructions: [
          "Спина и таз прижаты к платформе, стопы на ширине плеч.",
          "Опускайся до угла 90° в колене или ниже, если позволяет таз.",
          "Не отрывай поясницу от спинки в нижней точке.",
        ],
      },
      goblet_squat: {
        name: "Приседания с гантелью у груди",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["abs"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 1 },
        reps: { min: 10, max: 12 },
        benefit: "проще всего держать спину прямой, не нужна стойка",
        instructions: [
          "Держи гантель вертикально у груди, локти вниз.",
          "Садись между колен, корпус остаётся вертикальным.",
          "Не роняй грудь вперёд, когда устанешь.",
        ],
      },
      leg_press_plates: {
        name: "Жим ногами в тренажёре с блинами (45°)",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 10, max: 12 },
        benefit: "большой вес без нагрузки на спину",
        related: ["back_squat"],
        asset: crossFade(EXERCISE_FRAMES.leg_press_plates),
        instructions: [
          "Стопы на ширине таза на середине платформы, поясница прижата.",
          "Опускай платформу до угла 90° в колене, не отрывая таз.",
          "Не выключай колени полностью в верхней точке.",
        ],
      },
      leg_press_stack: {
        name: "Жим ногами в тренажёре с блоком",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "вес меняется шпилькой, удобно для дроп-сетов",
        instructions: [
          "Сядь, прижми спину к спинке, стопы на ширине таза.",
          "Выжимай платформу ногами, не выключая колени до конца.",
          "Возвращай платформу медленно, до угла 90° в колене.",
        ],
      },
    },
  },
  {
    exercises: {
      bulgarian_split_squat: {
        name: "Болгарские сплит-приседания с гантелями",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings", "abs"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 8, max: 12 },
        benefit: "грузит ногу поодиночке и растягивает ягодицу",
        instructions: [
          "Задняя нога на скамье, передняя в шаге впереди.",
          "Опускайся вниз, пока бедро передней ноги не станет параллельно полу.",
          "Держи корпус чуть наклонённым вперёд и не заваливайся на носок.",
        ],
      },
      smith_bulgarian_split_squat: {
        name: "Болгарские сплит-приседания в Смите",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["smith", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "равновесие держать не нужно — можно брать больше вес",
        instructions: [
          "Поставь скамью под гриф, задняя нога на скамье.",
          "Опускайся строго вниз, гриф лежит на трапециях.",
          "Подбери положение передней стопы так, чтобы колено не уходило за носок.",
        ],
      },
      walking_lunge: {
        name: "Шагающие выпады с гантелями",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings", "calves"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "длинная амплитуда и нагрузка на ягодицы в шаге",
        asset: crossFade(EXERCISE_FRAMES.walking_lunge),
        instructions: [
          "Гантели в опущенных руках, корпус вертикально.",
          "Шагай вперёд и опускай заднее колено почти до пола.",
          "Отталкивайся передней пяткой, не заваливая колено внутрь.",
        ],
      },
      dumbbell_lunge: {
        name: "Выпады с гантелями на месте",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "не нужно место для прохода по залу",
        asset: crossFade(EXERCISE_FRAMES.dumbbell_lunge),
        instructions: [
          "Одна нога впереди, вес распределён на обе стопы.",
          "Опускайся вниз до угла 90° в обоих коленях.",
          "Держи корпус вертикально и не отталкивайся задней ногой.",
        ],
      },
      barbell_lunge: {
        name: "Выпады со штангой на месте",
        primaryMuscles: ["quadriceps", "glutes"],
        secondaryMuscles: ["hamstrings", "abs"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "больше вес, чем с гантелями, и свободные кисти",
        asset: crossFade(EXERCISE_FRAMES.barbell_lunge),
        instructions: [
          "Штанга на трапециях, стопы в шаге друг от друга.",
          "Опускайся вниз, удерживая корпус вертикально.",
          "Начинай с лёгкого веса: равновесие здесь сложнее, чем в приседе.",
        ],
      },
      step_up: {
        name: "Зашагивания на скамью с гантелями",
        primaryMuscles: ["glutes", "quadriceps"],
        secondaryMuscles: ["hamstrings", "calves"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 10, max: 12 },
        benefit: "ягодицы включаются сильнее, чем в выпадах",
        asset: crossFade(EXERCISE_FRAMES.step_up),
        instructions: [
          "Поставь стопу на скамью целиком, высота — до угла 90° в колене.",
          "Вставай за счёт верхней ноги, не отталкиваясь нижней.",
          "Опускайся медленно, контролируя спуск.",
        ],
      },
    },
  },
  {
    exercises: {
      leg_extension: {
        name: "Разгибание ног в тренажёре",
        primaryMuscles: ["quadriceps"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "единственная чистая изоляция квадрицепса",
        asset: crossFade(EXERCISE_FRAMES.leg_extension),
        instructions: [
          "Ось тренажёра на уровне колена, валик на голени над стопой.",
          "Разгибай ноги до прямых, коротко задержись вверху.",
          "Не бросай вес вниз и не отрывай таз от сиденья.",
        ],
      },
    },
  },
  {
    exercises: {
      lying_leg_curl_stack: {
        name: "Сгибание ног лёжа в тренажёре с блоком",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["calves"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "базовая изоляция задней поверхности бедра",
        asset: crossFade(EXERCISE_FRAMES.lying_leg_curl_stack),
        instructions: [
          "Ляг так, чтобы колени были на краю подушки, валик над пятками.",
          "Сгибай ноги до касания валиком ягодиц.",
          "Не отрывай таз от подушки, помогая себе поясницей.",
        ],
      },
      lying_leg_curl_plates: {
        name: "Сгибание ног лёжа в тренажёре с блинами",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["calves"],
        equipment: ["machine"],
        load: { type: "plates", sides: 1 },
        reps: { min: 10, max: 12 },
        benefit: "жёстче нагрузка в верхней точке",
        instructions: [
          "Выстави упор так, чтобы колени свисали с края подушки.",
          "Сгибай ноги подконтрольно, без рывка от блинов.",
          "Опускай вес до почти прямых ног, сохраняя натяжение.",
        ],
      },
      seated_leg_curl: {
        name: "Сгибание ног сидя в тренажёре",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["calves"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "бедро согнуто — задняя поверхность растянута сильнее",
        asset: crossFade(EXERCISE_FRAMES.seated_leg_curl),
        instructions: [
          "Прижми бёдра валиком, спину — к спинке, валик над пятками.",
          "Сгибай ноги под себя до упора, держа таз на месте.",
          "Возвращай вес медленно, не выпрямляя ноги рывком.",
        ],
      },
      standing_leg_curl: {
        name: "Сгибание ноги стоя в тренажёре",
        primaryMuscles: ["hamstrings"],
        secondaryMuscles: ["calves"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "каждая нога отдельно, видно отставание",
        asset: crossFade(EXERCISE_FRAMES.standing_leg_curl),
        instructions: [
          "Встань в тренажёр, валик над пяткой рабочей ноги.",
          "Сгибай ногу, не двигая бедром и не прогибая поясницу.",
          "Делай одинаковое число повторов на обе ноги.",
        ],
      },
    },
  },
  {
    exercises: {
      barbell_hip_thrust: {
        name: "Ягодичный мостик со штангой",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings", "quadriceps"],
        equipment: ["barbell", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "самая тяжёлая нагрузка именно на ягодицы",
        instructions: [
          "Лопатки на скамье, штанга на складке бёдер через мягкую подкладку.",
          "Выталкивай таз вверх до прямой линии корпуса и бёдер.",
          "Не переразгибай поясницу — подбородок держи опущенным.",
        ],
      },
      hip_thrust_machine: {
        name: "Ягодичный мостик в тренажёре с блинами",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 10, max: 12 },
        benefit: "не нужно заряжать штангу на себя",
        instructions: [
          "Сядь, прижми спину к упору, валик на складке бёдер.",
          "Выталкивай таз вперёд, сжимая ягодицы в верхней точке.",
          "Возвращайся медленно, не роняя вес.",
        ],
      },
      cable_kickback: {
        name: "Отведение ноги назад в кроссовере",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "изолирует ягодицу и растягивает её в старте",
        asset: crossFade(EXERCISE_FRAMES.cable_kickback),
        instructions: [
          "Манжета на щиколотке, держись за стойку, корпус чуть наклонён.",
          "Отводи ногу назад за счёт ягодицы, не прогибая поясницу.",
          "Возвращай ногу медленно, не отпуская натяжение.",
        ],
      },
      glute_machine_kickback: {
        name: "Отведение ноги назад в тренажёре",
        primaryMuscles: ["glutes"],
        secondaryMuscles: ["hamstrings"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "корпус зафиксирован, работает только ягодица",
        instructions: [
          "Упрись корпусом в подушку, рабочая стопа на платформе.",
          "Толкай платформу назад до полного разгибания бедра.",
          "Не прогибай поясницу, добирая амплитуду.",
        ],
      },
      hip_abduction: {
        name: "Отведение бёдер в тренажёре сидя",
        primaryMuscles: ["abductors"],
        secondaryMuscles: ["glutes"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "единственная нормальная нагрузка на средние ягодичные",
        asset: crossFade(EXERCISE_FRAMES.hip_abduction),
        instructions: [
          "Сядь, прижми спину к спинке, упоры снаружи колен.",
          "Разводи колени до упора и коротко задержись.",
          "Сводить ноги обратно нужно медленно, а не бросать.",
        ],
      },
      hip_adduction: {
        name: "Приведение бёдер в тренажёре сидя",
        primaryMuscles: ["adductors"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "закрывает приводящие, которые больше нечем грузить",
        asset: crossFade(EXERCISE_FRAMES.hip_adduction),
        instructions: [
          "Сядь, упоры с внутренней стороны колен, спина прижата.",
          "Своди колени до касания, держа паузу в конце.",
          "Разводи ноги обратно медленно, не до боли в растяжении.",
        ],
      },
    },
  },
  {
    exercises: {
      standing_calf_raise_stack: {
        name: "Подъёмы на носки стоя в тренажёре с блоком",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "икры с прямой ногой и быстрой сменой веса",
        asset: crossFade(EXERCISE_FRAMES.standing_calf_raise_stack),
        instructions: [
          "Носки на платформе, пятки свисают, плечи под упорами.",
          "Поднимайся максимально высоко и опускайся до растяжения.",
          "Не сгибай колени, чтобы подкинуть вес.",
        ],
      },
      standing_calf_raise_plates: {
        name: "Подъёмы на носки стоя в тренажёре с блинами",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 12, max: 15 },
        benefit: "икры любят большой вес, а блинов можно навесить много",
        instructions: [
          "Встань носками на платформу, упоры плотно на плечах.",
          "Работай полной амплитудой: вниз до растяжения, вверх на носок.",
          "Держи темп ровным, без подпрыгиваний.",
        ],
      },
      seated_calf_raise: {
        name: "Подъёмы на носки сидя в тренажёре",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "plates", sides: 1 },
        reps: { min: 12, max: 15 },
        benefit: "согнутое колено переносит работу на камбаловидную",
        asset: crossFade(EXERCISE_FRAMES.seated_calf_raise),
        instructions: [
          "Колени под валик, носки на платформе, пятки свободны.",
          "Поднимайся на носки до упора и задерживайся на секунду.",
          "Опускай пятки до полного растяжения.",
        ],
      },
      smith_calf_raise: {
        name: "Подъёмы на носки в Смите",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: ["smith"],
        load: { type: "barbell" },
        reps: { min: 12, max: 15 },
        benefit: "если тренажёр на икры занят",
        instructions: [
          "Подложи под носки блин или степ, гриф на трапециях.",
          "Поднимайся на носки, держа колени прямыми.",
          "Опускай пятки ниже уровня платформы.",
        ],
      },
      leg_press_calf_raise: {
        name: "Подъёмы на носки в жиме ногами",
        primaryMuscles: ["calves"],
        secondaryMuscles: [],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 12, max: 15 },
        benefit: "не нужно держать вес на плечах",
        asset: crossFade(EXERCISE_FRAMES.leg_press_calf_raise),
        instructions: [
          "Поставь носки на нижний край платформы, колени слегка согнуты.",
          "Выжимай платформу стопой, полностью разгибая голеностоп.",
          "Держи страховочные упоры включёнными на случай срыва стопы.",
        ],
      },
      dumbbell_calf_raise: {
        name: "Подъёмы на носки с гантелями стоя",
        primaryMuscles: ["calves"],
        secondaryMuscles: ["forearms"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 15, max: 20 },
        benefit: "работает где угодно, нужен только блин под носки",
        instructions: [
          "Встань носками на блин или степ, гантели в опущенных руках.",
          "Поднимайся на носки максимально высоко.",
          "Держись свободной рукой за стойку, если теряешь равновесие.",
        ],
      },
    },
  },
];
