import { EXERCISE_FRAMES } from "../frames.generated.ts";
import { crossFade } from "./assets.ts";
import type { ExerciseGroup } from "./types.ts";

export const SHOULDER_GROUPS: ExerciseGroup[] = [
  {
    exercises: {
      overhead_press: {
        name: "Жим штанги стоя",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps", "abs", "upper_back"],
        equipment: ["barbell"],
        load: { type: "barbell" },
        reps: { min: 6, max: 8 },
        benefit: "больше рабочий вес, работает всё тело",
        instructions: [
          "Штанга на передних дельтах, локти чуть впереди грифа.",
          "Выжимай вверх, проводя штангу близко к лицу, и уводи голову назад.",
          "Не прогибай поясницу: рёбра держи опущенными, ягодицы напряжены.",
        ],
      },
      dumbbell_shoulder_press: {
        name: "Жим гантелей сидя вверх",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 8, max: 12 },
        benefit: "спинка снимает нагрузку с поясницы",
        instructions: [
          "Сядь, прижми поясницу к спинке, гантели на уровне ушей.",
          "Выжимай вверх, сводя гантели над головой, но не сталкивая их.",
          "Опускай до уровня подбородка, не роняя локти слишком низко.",
        ],
      },
      smith_shoulder_press: {
        name: "Жим в Смите сидя вверх",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: ["smith", "bench"],
        load: { type: "barbell" },
        reps: { min: 8, max: 12 },
        benefit: "можно дожимать до отказа без страхующего",
        instructions: [
          "Поставь скамью так, чтобы гриф опускался к ключицам.",
          "Выжимай вверх, не выводя голову далеко вперёд.",
          "Опускай гриф до уровня подбородка и не бей им по ключицам.",
        ],
      },
      shoulder_press_stack: {
        name: "Жим вверх в тренажёре с блоком",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 10, max: 12 },
        benefit: "самый безопасный способ дожать плечи в конце тренировки",
        instructions: [
          "Отрегулируй сиденье: ручки на уровне плеч.",
          "Выжимай вверх, не выключая локти полностью.",
          "Держи поясницу прижатой к спинке.",
        ],
      },
      shoulder_press_plates: {
        name: "Жим вверх в тренажёре с блинами",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["triceps"],
        equipment: ["machine"],
        load: { type: "plates", sides: 2 },
        reps: { min: 8, max: 12 },
        benefit: "тяжёлый жим с фиксированной спиной",
        instructions: [
          "Сядь плотно, ручки должны стартовать на уровне плеч.",
          "Выжимай вверх по дуге, лопатки прижаты к спинке.",
          "Опускай медленно, не позволяя блинам тянуть руки вниз.",
        ],
      },
    },
  },
  {
    exercises: {
      lateral_raise: {
        name: "Махи гантелями в стороны стоя",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["traps"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "основное движение на среднюю дельту",
        asset: crossFade(EXERCISE_FRAMES.lateral_raise),
        instructions: [
          "Лёгкий наклон корпуса вперёд, локти чуть согнуты и зафиксированы.",
          "Поднимай гантели до уровня плеч, ведя движение локтями.",
          "Не закидывай вес рывком и не поднимай плечи к ушам.",
        ],
      },
      seated_lateral_raise: {
        name: "Махи гантелями в стороны сидя",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["traps"],
        equipment: ["dumbbell", "bench"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "корпус выключен, читинг невозможен",
        instructions: [
          "Сядь на край скамьи, гантели по бокам, спина прямая.",
          "Разводи руки до уровня плеч, мизинцы чуть выше больших пальцев.",
          "Не качай корпусом и не подбрасывай вес снизу.",
        ],
      },
      cable_lateral_raise: {
        name: "Махи в стороны на нижнем блоке одной рукой",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["traps"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "натяжение с самой нижней точки, где гантель ничего не даёт",
        instructions: [
          "Встань боком к стойке, трос идёт перед корпусом.",
          "Отводи руку в сторону до уровня плеча, локоть чуть согнут.",
          "Возвращай медленно, не давая тросу утянуть руку вниз.",
        ],
      },
      lateral_raise_machine_seated: {
        name: "Махи в стороны в тренажёре сидя",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["traps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "траектория задана, можно работать до отказа",
        instructions: [
          "Отрегулируй сиденье: ось тренажёра на уровне плечевого сустава.",
          "Дави локтями в подушки и разводи руки до уровня плеч.",
          "Не поднимай плечи и не помогай наклоном корпуса.",
        ],
      },
      lateral_raise_machine_standing: {
        name: "Махи в стороны в тренажёре стоя",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["traps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "свободнее корпус, удобнее выйти в стартовую позицию",
        instructions: [
          "Встань в тренажёр, упоры под предплечьями или в ладонях.",
          "Разводи руки до уровня плеч, корпус держи неподвижным.",
          "Опускай медленно, не роняя вес в нижнюю точку.",
        ],
      },
    },
  },
  {
    exercises: {
      reverse_pec_deck: {
        name: "Разведения на задние дельты в тренажёре",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["upper_back", "traps"],
        equipment: ["machine"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "изолирует задние дельты лучше всего",
        instructions: [
          "Сядь грудью к спинке, ручки на уровне плеч.",
          "Разводи руки назад по дуге, локти почти прямые.",
          "Не своди лопатки до отказа — работать должны дельты, не спина.",
        ],
      },
      bent_over_dumbbell_raise: {
        name: "Разведение гантелей в наклоне на задние дельты",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["upper_back", "traps"],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "не нужен свободный тренажёр",
        instructions: [
          "Наклонись почти параллельно полу, спина прямая.",
          "Разводи гантели в стороны до уровня плеч, локти чуть согнуты.",
          "Не выпрямляйся во время подхода и не тяни гантели к поясу.",
        ],
      },
      cable_reverse_fly: {
        name: "Разведение в кроссовере через стороны",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["upper_back"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "ровное натяжение во всей амплитуде",
        instructions: [
          "Возьми верхние блоки крест-накрест, руки перед собой.",
          "Разводи руки назад и в стороны, грудь раскрыта.",
          "Не сгибай локти сильнее, чем в старте.",
        ],
      },
      face_pull: {
        name: "Тяга канатной рукояти к лицу в кроссовере",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: ["upper_back", "traps"],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "заодно разворачивает плечи назад после жимов",
        instructions: [
          "Блок на уровне лица, канат в руках, шаг назад до натяжения.",
          "Тяни канат к лицу, разводя концы в стороны, локти выше кистей.",
          "Не превращай в тягу к груди: локти идут в стороны, а не вниз.",
        ],
      },
    },
  },
  {
    exercises: {
      front_raise: {
        name: "Подъём гантелей перед собой",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: ["dumbbell"],
        load: { type: "dumbbell", count: 2 },
        reps: { min: 12, max: 15 },
        benefit: "точечно на переднюю дельту",
        instructions: [
          "Гантели перед бёдрами, руки прямые, корпус неподвижен.",
          "Поднимай до уровня плеч, не выше.",
          "Не раскачивайся и не поднимай гантели рывком от бёдер.",
        ],
      },
      cable_front_raise: {
        name: "Подъём рукояти перед собой на нижнем блоке",
        primaryMuscles: ["shoulders"],
        secondaryMuscles: [],
        equipment: ["cable"],
        load: { type: "stack" },
        reps: { min: 12, max: 15 },
        benefit: "нагрузка не пропадает в нижней точке",
        instructions: [
          "Встань спиной к стойке, рукоять нижнего блока перед бёдрами.",
          "Поднимай прямые руки до уровня плеч.",
          "Держи корпус вертикально, не отклоняясь назад.",
        ],
      },
    },
  },
];
